# Dockerfile to containerise the stream harvester .

# Default version of python3 used in the chosen instance image.
FROM python:3.6.9

# Working directory of the stream harvester.
WORKDIR /tweet_harvester_stream

# Required data.
COPY data /tweet_harvester_stream/data/

# Source code.
COPY tweet_harvester_stream.py /tweet_harvester_stream

# Upgrade pip.
RUN pip3 install --upgrade pip

# Install tweepy to harvest tweets.
RUN pip3 install --trusted-host pypi.python.org tweepy

# Install couchdb to store harvested tweets.
RUN pip3 install --trusted-host pypi.python.org couchdb

# Install Python GDAL dependencies.
RUN apt-get update -y
RUN apt-get install -y gdal-bin
RUN apt-get install -y libgdal-dev

# Update C env vars so compiler can find gdal.
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

# gdal
RUN pip3 install GDAL==2.4.2

# Farmers rejoice in stream!.
CMD ["python3", "tweet_harvester_stream.py", "{{ twitter_hashtags }}", "{{ twitter_api_key }}","{{ twitter_api_secret_key }}","{{ twitter_access_token }}","{{ twitter_access_token_secret }}","{{ couchdb_user }}", "{{ couchdb_password }}", "{{ ansible_default_ipv4.address }}", "{{ couchdb_port }}"]
