---
# Code adapted from Ansible Demo 1, COMP90024 Semester 1 2020, Workshop 5.

# Create an instance on NeCTAR
- name: Create instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{item.volumes}}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: '{{ instances }}'
  register: os_instance

- debug:
    msg: "Instance {{ instance_name }} has been created. IP address is {{ os_instance.openstack.public_v4 }}."
  when: os_instance.openstack is defined

- name: Wait for connection
  wait_for:
    host: '{{ item.openstack.public_v4 }}'
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Add hosts to Ansible in-memory inventory.
- name: Add hosts
  add_host:
    name: '{{ item.openstack.public_v4 }}'
    groups: COMP90024
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined

# Save the IP addresses in a file.
- name: Save IP addresses
  become: yes
  local_action:
    module: lineinfile
    path: ./../deployment/hosts
    line: '{{ item.openstack.public_v4 }}'
    insertbefore: EOF
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined
