---
# Setup twitter harvesters.

# Remove old tweet_harvester directory.
- name: Remove old harvester directory
  become: yes
  command: rm -r tweet_harvester
  args: 
    chdir: /home/{{ansible_user}}/

# Create tweet_harvester directory.
- name: Create harvester directory
  become: yes
  file:
    path: '{{ harvester_dir }}'
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# Upload harvester Dockerfile to instance(s).
- name: Upload tweet_harvester Dockerfile
  become: yes
  copy:
    src: './roles/instance-tweet-harvester/templates/Dockerfile.j2'
    dest: '{{ harvester_dir }}/Dockerfile'
    mode: 700
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

# Upload local tweet_harvester directory to remote.
- name: Upload local tweet_harvester directory to remove
  become: yes
  copy:
    src: '../tweet_harvester/'
    dest: '{{ harvester_dir }}'
    mode: 700
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

# Build the harvester from Dockerfile.
- name: Build harvester
  become: yes
  command: 'docker build -f Dockerfile -t {{ harvester_name }} .'
  args: 
    chdir: '{{ harvester_dir }}'

# TODO: run asynchronously 
# Start up the harvester.
- name: Start harvester
  become: yes
  command: 'docker run -d -it {{ harvester_name }}'
  args: 
    chdir: '{{ harvester_dir }}'

