# Sets the common variables for NeCTAR instance deployment.

# Availability zone.
availability_zone: melbourne-qh2-uom

# Volumes.
volumes:
  - vol_name: comp90024_vol1
    vol_size: 60
  - vol_name: comp90024_vol2
    vol_size: 60
  - vol_name: comp90024_vol3
    vol_size: 60
  - vol_name: comp90024_vol4
    vol_size: 60

# Security groups.
security_groups:
  - name: ssh
    description: Security group for SSH access."
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    #remote_ip_prefix: 128.250.0.0/16 # Allows access from unimelb only.
    remote_ip_prefix: 0.0.0.0/0 # Allows access from everywhere.

  - name: http
    description: "Security group for HTTP access."
    protocol: tcp 
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: CouchDB - Standard clustered port for all HTTP API requests
    description: "Security group for CouchDB access."
    protocol: tcp 
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: CouchDB - Erlang port mapper daemon (epmd)
    description: "Security group for CouchDB access."
    protocol: tcp 
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  
  - name: CouchDB cluster communication
    description: "Security group for CouchDB cluster communication."
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

  - name: Secure Docker client communication. Required for Docker Machine to work. 
    description: "Security group for Secure Docker client communication."
    protocol: tcp
    port_range_min: 2376
    port_range_max: 2376
    remote_ip_prefix: 0.0.0.0/0
     
  - name: Docker Swarm - cluster management communications
    description: "Security group for Docker Swarm cluster management communications."
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0

  - name: Docker Swarm - TCP communication among nodes 
    description: "Security group for Docker Swarm - TCP communication among nodes."
    protocol: tcp
    port_range_min: 7946
    port_range_max: 7946
    remote_ip_prefix: 0.0.0.0/0

  - name: Docker Swarm - UDP communication among nodes 
    description: "Security group for Docker Swarm - UDP communication among nodes."
    protocol: udp
    port_range_min: 7946
    port_range_max: 7946
    remote_ip_prefix: 0.0.0.0/0

  - name : Docker Swarm - UDP for overlay network traffic
    description: " Security group for Docker Swarm - UDP for overlay network traffic."
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_ip_prefix: 0.0.0.0/0

  - name: WebServer
    description: "Security group for Web Server access."
    protocol: tcp 
    port_range_min: 5555
    port_range_max: 5555
    remote_ip_prefix: 0.0.0.0/0

    - name: Front-end app
    description: "Security group for front-end app access."
    protocol: tcp 
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

# Instances.
instances:
  - name: comp90024-1
    volumes: ['comp90024_vol1']
  - name: comp90024-2
    volumes: ['comp90024_vol2']
  - name: comp90024-3
    volumes: ['comp90024_vol3']
  - name: comp90024-4
    volumes: ['comp90024_vol4']

instance_image: 215f9775-483c-4e0a-b703-d21a5c966f2e
instance_key_name: comp90024-67
instance_flavor: uom.mse.2c9g

