---
# Setup a Docker Swarm.

# Setup the master node of the swarm.
#- name: Setup master node
  #when: ansible_hostname == 'comp90024-1'
  #become: yes
  #shell: docker swarm init

# Get the join token of the manager.
- name: Get join token
  when: ansible_hostname == 'comp90024-1'
  become: yes
  shell: docker swarm join-token manager | grep "docker swarm join"
  register: output

# Save the created join token in a file.
- name: Modify join token
  when: ansible_hostname == 'comp90024-1'
  become: yes
  local_action:
    module: lineinfile
    dest: ./join_token.yaml
    regexp: 'join_token:'
    line: 'join_token: {{ output.stdout }}'

# Load the created join token.
- name: Reload join token
  when: ansible_hostname != 'comp90024-1'
  include_vars: ./join_token.yaml

# If node is not a manager, join the swarm.
- name: Join the swarm
  when: ansible_hostname != 'comp90024-1'
  become: yes
  command: "{{ join_token }}"

