---
# Code adapted from Ansible Demo 1, COMP90024 Semester 1 2020, Workshop 5.

# Create volume snapshots.
- name: Create volume snapshots
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name }}'
    display_name: "{{ item.vol_name }}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes 
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ volumes }}''

