- hosts: localhost
  vars_files:
    - host_vars/nectar-vars.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volumes
    - role: openstack-security-groups
    - role: openstack-instances
    #- role: openstack-volume-snapshots # Got an error creating snapshot, need debugging first.

